/* ============================================================================
 * Prove It! — game content
 * ----------------------------------------------------------------------------
 * This is the ONLY file you edit to add categories & answers. No code changes
 * needed. It's loaded as a plain <script> (works when you just open index.html
 * — no server required).
 *
 * STRUCTURE:  group → categories → items
 *
 *   CATEGORY_GROUPS = {
 *     "GroupName": {                 // a broad group = one checkbox on the lobby
 *       emoji: "🎬",
 *       cats: [                      // specific categories; one is picked per round
 *         { name: "Category shown to the player", items: [ ...answers... ] },
 *       ],
 *     },
 *   }
 *
 * EACH ITEM is one of:
 *   "Canonical Name"                         → no aliases
 *   ["Canonical Name", "alias", "alias2"]    → all accepted, but count as ONE item
 *
 *   • The FIRST entry is the display name shown when the player gets it right.
 *   • Aliases let "cr7" / "ronaldo" / "cristiano ronaldo" all match one player.
 *   • Matching is case-, space-, and accent-insensitive ("mbappe" matches "Mbappé"),
 *     so you usually don't need plain-text aliases for accents.
 *
 * OPTIONAL per-category flag:
 *   • exact: true  → this is a complete, finite list (e.g. US States). On an
 *     over-claim the game may reveal the exact count. Omit it for open-ended
 *     categories (Car Brands, Rappers…) so the cap stays a generic "try again".
 *
 * TO ADD:
 *   • a category  → add a { name, items } object to a group's `cats` array
 *   • a group     → add a new top-level key with { emoji, cats: [...] }
 *   • answers     → add strings/alias-arrays to a category's `items` array
 * ========================================================================== */

const CATEGORY_GROUPS = {
  Sports: { emoji: "⚽", cats: [
    { name: "Football (Soccer) Players", items: [
      ["Lionel Messi","messi","leo messi","la pulga"], ["Cristiano Ronaldo","ronaldo","cristiano","cr7"],
      ["Neymar","neymar jr"], ["Kylian Mbappé","mbappe","kylian"], ["Erling Haaland","haaland","erling"],
      ["Karim Benzema","benzema","karim"], ["Robert Lewandowski","lewandowski","lewy"], ["Mohamed Salah","salah","mo salah"],
      "Harry Kane", ["Kevin De Bruyne","de bruyne","kdb"], ["Luka Modrić","modric"], ["Antoine Griezmann","griezmann","grizou"],
      ["Jude Bellingham","bellingham","jude"], ["Vinícius Júnior","vinicius","vini","vini jr","vinicius junior"],
      ["Bukayo Saka","saka"], ["Phil Foden","foden"], ["Rodri","rodrigo hernandez"], ["Pedri","pedri gonzalez"],
      ["Gavi","pablo gavi"], ["Jamal Musiala","musiala"], ["Florian Wirtz","wirtz"], ["Marcus Rashford","rashford"],
      ["Toni Kroos","kroos"], ["Riyad Mahrez","mahrez"], ["Heung-min Son","son","sonny","son heung-min"],
      ["Victor Osimhen","osimhen"], ["Lautaro Martínez","lautaro","el toro"], ["Julián Álvarez","julian alvarez","la araña"],
      ["Luis Suárez","suarez","luis suarez"], ["Paul Pogba","pogba"], ["Sergio Ramos","ramos"], ["Raphaël Varane","varane"],
      ["Virgil van Dijk","van dijk","vvd"], ["Sadio Mané","mane","sadio mane"], ["Bernardo Silva","bernardo"],
      ["Rúben Dias","ruben dias"], ["Martin Ødegaard","odegaard"], ["Declan Rice","rice"],
      ["Federico Valverde","valverde","fede valverde"], ["Rodrygo","rodrygo goes"], ["Pedro Neto","neto"],
      ["Cole Palmer","palmer"], ["Rafael Leão","leao","rafael leao"], ["Khvicha Kvaratskhelia","kvaratskhelia","kvara"],
      ["Bruno Fernandes","bruno fernandes"], ["Thomas Müller","muller","thomas muller"], ["Joshua Kimmich","kimmich"],
      ["Manuel Neuer","neuer"], ["Antonio Rüdiger","rudiger"], ["Kai Havertz","havertz"], ["İlkay Gündoğan","gundogan"],
      ["Leroy Sané","sane","leroy sane"], ["Serge Gnabry","gnabry"], ["Dušan Vlahović","vlahovic"],
      ["Achraf Hakimi","hakimi"], ["Nicolò Barella","barella"], ["Federico Chiesa","chiesa"],
      ["Gianluigi Donnarumma","donnarumma","gigio"], ["Ousmane Dembélé","dembele"], ["Aurélien Tchouaméni","tchouameni"],
      ["Eduardo Camavinga","camavinga"], ["Christopher Nkunku","nkunku"], ["Mason Mount","mount"],
      ["Trent Alexander-Arnold","alexander-arnold","taa","trent"], ["Andrew Robertson","robertson"],
      ["Alisson Becker","alisson"], ["Ederson","ederson moraes"], ["Jack Grealish","grealish"],
      ["Dominik Szoboszlai","szoboszlai"], ["Alexis Mac Allister","mac allister"], ["Enzo Fernández","enzo fernandez"],
      ["Moisés Caicedo","caicedo"], ["Pelé","edson arantes"], ["Diego Maradona","maradona","el pibe de oro"],
      ["Johan Cruyff","cruyff"], ["Franz Beckenbauer","beckenbauer","der kaiser"], ["Zinedine Zidane","zidane","zizou"],
      ["Ronaldinho","ronaldinho gaucho","dinho"], ["Ronaldo Nazário","ronaldo nazario","r9","o fenomeno","el fenomeno"],
      ["Romário","romario"], ["Roberto Baggio","baggio"], ["Paolo Maldini","maldini"], ["Fabio Cannavaro","cannavaro"],
      ["Andrea Pirlo","pirlo"], ["Steven Gerrard","gerrard","stevie g"], ["Frank Lampard","lampard","lamps"],
      ["Paul Scholes","scholes"], ["Thierry Henry","henry","titi"], ["Didier Drogba","drogba"],
      ["Andriy Shevchenko","shevchenko","sheva"], ["Luís Figo","figo"], ["Raúl","raul gonzalez"],
      ["Iker Casillas","casillas","san iker"], ["Gianluigi Buffon","buffon","gigi buffon"], ["Kaká","kaka","ricardo kaka"],
      ["Zlatan Ibrahimović","ibrahimovic","zlatan","ibra"], ["Wayne Rooney","rooney","wazza"],
      ["David Beckham","beckham","becks"], ["Xavi","xavi hernandez"], ["Andrés Iniesta","iniesta"],
      ["Carles Puyol","puyol"], ["Francesco Totti","totti"], ["Alessandro Del Piero","del piero"], ["George Best","best"],
      ["Eusébio","eusebio"], ["Michel Platini","platini"], ["Marco van Basten","van basten"], ["Ruud Gullit","gullit"],
      ["Lothar Matthäus","matthaus"], ["Gerd Müller","gerd muller","der bomber"], ["Bobby Charlton","charlton"],
      ["Roberto Carlos","roberto carlos"], "Cafu", ["Ryan Giggs","giggs"], ["Edwin van der Sar","van der sar"],
      ["Petr Čech","cech"], ["Rio Ferdinand","ferdinand"], ["Patrick Vieira","vieira"], ["Dennis Bergkamp","bergkamp"],
      ["Samuel Eto'o","eto'o","etoo","samuel etoo"], ["Yaya Touré","yaya toure","yaya"], ["David Villa","villa","el guaje"],
      ["Fernando Torres","torres","el niño"], ["Sergio Agüero","aguero","kun","kun aguero"], ["Gareth Bale","bale"],
      ["Eden Hazard","hazard"], ["Edinson Cavani","cavani","el matador"],
    ]},
    { name: "NBA Players", items: [
      ["LeBron James","lebron","king james","the king"], ["Stephen Curry","curry","steph","chef curry"],
      ["Kevin Durant","durant","kd","the slim reaper"], ["Giannis Antetokounmpo","giannis","greek freak"],
      ["Nikola Jokić","jokic","joker","the joker"], ["Joel Embiid","embiid","the process"], ["Luka Dončić","luka","doncic"],
      ["Jayson Tatum","tatum"], ["Jalen Brunson","brunson"], ["Anthony Edwards","edwards","ant","ant-man"],
      ["Victor Wembanyama","wembanyama","wemby"], ["Devin Booker","booker","book"], ["Ja Morant","ja","morant"],
      ["Zion Williamson","zion"], ["Donovan Mitchell","donovan mitchell","spida"], ["Tyrese Haliburton","haliburton"],
      ["Shai Gilgeous-Alexander","gilgeous-alexander","sga","shai"], ["Kawhi Leonard","kawhi","leonard","the klaw"],
      ["Paul George","paul george","pg13","pg"], ["Jimmy Butler","jimmy butler","jimmy buckets"],
      ["Damian Lillard","lillard","dame","dame time"], ["Anthony Davis","anthony davis","ad","the brow"],
      ["Trae Young","trae","ice trae"], ["James Harden","harden","the beard"], ["Kyrie Irving","kyrie","uncle drew"],
      ["Klay Thompson","klay"], ["Draymond Green","draymond"], ["Russell Westbrook","westbrook","russ","brodie"],
      ["Chris Paul","chris paul","cp3"], ["Bradley Beal","beal"], ["Karl-Anthony Towns","towns","kat"],
      ["Rudy Gobert","gobert"], ["Bam Adebayo","bam","adebayo"], ["DeMar DeRozan","derozan","demar"],
      ["Zach LaVine","lavine"], ["Pascal Siakam","siakam","spicy p"], ["Jaylen Brown","jaylen brown"],
      ["Domantas Sabonis","sabonis"], ["Jrue Holiday","jrue","holiday"], ["Brandon Ingram","ingram"],
      ["LaMelo Ball","lamelo"], ["De'Aaron Fox","de'aaron fox","fox","swipa"], ["Paolo Banchero","banchero","paolo"],
      ["Scottie Barnes","scottie barnes"], ["Cade Cunningham","cade","cunningham"],
      ["Michael Jordan","jordan","mj","air jordan","his airness"], ["Kobe Bryant","kobe","black mamba","mamba"],
      ["Shaquille O'Neal","shaq","shaquille oneal","the big aristotle"], ["Magic Johnson","magic"],
      ["Larry Bird","larry bird","larry legend"], ["Kareem Abdul-Jabbar","kareem","abdul-jabbar","cap"],
      ["Wilt Chamberlain","wilt","the stilt"], ["Bill Russell","bill russell"],
      ["Tim Duncan","duncan","the big fundamental"], ["Dirk Nowitzki","dirk","nowitzki"],
      ["Kevin Garnett","garnett","kg","the big ticket"], ["Allen Iverson","iverson","ai","the answer"],
      ["Steve Nash","nash"], ["John Stockton","stockton"], ["Karl Malone","malone","the mailman"],
      ["Hakeem Olajuwon","olajuwon","hakeem","the dream"], ["Patrick Ewing","ewing"], ["Scottie Pippen","pippen","pip"],
      ["Charles Barkley","barkley","sir charles"], ["Julius Erving","julius erving","dr j","dr. j"],
      ["Dwyane Wade","wade","dwyane wade","flash"], ["Chris Bosh","bosh"], ["Carmelo Anthony","carmelo","melo"],
      ["Vince Carter","vince carter","vinsanity"], ["Tracy McGrady","mcgrady","t-mac"],
      ["Dwight Howard","dwight","howard","superman"], ["Paul Pierce","pierce","the truth"],
      ["Ray Allen","ray allen","jesus shuttlesworth"], ["Tony Parker","tony parker"], ["Manu Ginóbili","ginobili","manu"],
      ["Yao Ming","yao"], ["Dikembe Mutombo","mutombo"], ["Reggie Miller","reggie miller"],
      ["Gary Payton","gary payton","the glove"], ["Jason Kidd","jason kidd"], ["David Robinson","david robinson","the admiral"],
      ["Isiah Thomas","isiah thomas","zeke"], ["Clyde Drexler","drexler","clyde the glide"],
      ["Dominique Wilkins","wilkins"], ["Pete Maravich","maravich","pistol pete"], ["Jerry West","jerry west","the logo"],
      ["Oscar Robertson","oscar robertson","the big o"],
    ]},
  ]},
  Geography: { emoji: "🌍", cats: [
    { name: "Countries in Europe", items: [
      "France","Germany","Spain","Italy","Portugal",
      ["United Kingdom","uk","united kingdom","britain","great britain","england","scotland","wales"],
      "Ireland","Netherlands","Belgium","Switzerland","Austria","Poland","Sweden","Norway","Finland","Denmark","Iceland",
      "Greece","Turkey","Russia","Ukraine","Belarus", ["Czechia","czechia","czech republic"], "Slovakia","Hungary",
      "Romania","Bulgaria","Croatia","Serbia","Slovenia", ["Bosnia and Herzegovina","bosnia and herzegovina","bosnia"],
      "Montenegro", ["North Macedonia","north macedonia","macedonia"], "Kosovo","Albania","Estonia","Latvia","Lithuania",
      "Luxembourg","Malta","Cyprus","Moldova","Andorra","Liechtenstein","Monaco","San Marino",
      ["Vatican City","vatican city","vatican"],
    ]},
    { name: "US State Capitals", exact: true, items: [
      "Sacramento","Austin","Albany","Tallahassee","Springfield","Columbus","Atlanta","Denver","Boston","Phoenix",
      "Nashville","Raleigh","Madison","Lansing", ["Saint Paul","saint paul","st paul"], "Jefferson City",
      "Oklahoma City","Salt Lake City","Carson City","Boise","Helena","Cheyenne","Bismarck","Pierre","Topeka",
      "Lincoln","Des Moines","Indianapolis","Frankfort","Montgomery","Jackson","Baton Rouge","Little Rock",
      "Richmond","Annapolis","Dover","Trenton","Harrisburg","Hartford","Providence","Augusta","Concord",
      "Montpelier","Olympia","Salem","Honolulu","Juneau","Santa Fe","Columbia","Charleston",
    ]},
    { name: "US States", exact: true, items: [
      "Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia",
      "Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland",
      "Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire",
      "New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania",
      "Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington",
      "West Virginia","Wisconsin","Wyoming",
    ]},
    { name: "World Capitals", items: [
      ["Kabul","kabul"], ["Tirana","tirana"], ["Algiers","algiers"], ["Andorra la Vella","andorra la vella"], "Luanda",
      ["Saint John's","saint john's","st john's","st. john's"], "Buenos Aires", "Yerevan", "Canberra", "Vienna", "Baku",
      "Nassau", "Manama", ["Dhaka","dhaka","dacca"], "Bridgetown", "Minsk", "Brussels", "Belmopan",
      ["Porto-Novo","porto-novo","porto novo","cotonou"], "Thimphu", ["Sucre","sucre","la paz"], "Sarajevo", "Gaborone",
      "Brasília", "Bandar Seri Begawan", "Sofia", "Ouagadougou", ["Gitega","gitega","bujumbura"], "Praia", "Phnom Penh",
      "Yaoundé", "Ottawa", "Bangui", ["N'Djamena","n'djamena","ndjamena"], "Santiago", ["Beijing","beijing","peking"],
      "Bogotá", "Moroni", "Brazzaville", "Kinshasa", "San José", ["Yamoussoukro","yamoussoukro","abidjan"], "Zagreb",
      "Havana", "Nicosia", "Prague", "Copenhagen", ["Djibouti","djibouti","djibouti city"], "Roseau", "Santo Domingo",
      "Quito", "Cairo", "San Salvador", "Malabo", "Asmara", "Tallinn", ["Mbabane","mbabane","lobamba"], "Addis Ababa",
      "Suva", "Helsinki", "Paris", "Libreville", "Banjul", "Tbilisi", "Berlin", "Accra", "Athens",
      ["Saint George's","saint george's","st george's","st. george's"], "Guatemala City", "Conakry", "Bissau",
      "Georgetown", ["Port-au-Prince","port-au-prince","port au prince"], "Tegucigalpa", "Budapest",
      "Reykjavík", ["New Delhi","new delhi","delhi"], ["Jakarta","jakarta","nusantara"], "Tehran", "Baghdad", "Dublin",
      "Jerusalem", "Rome", "Kingston", "Tokyo", "Amman", ["Astana","astana","nur-sultan","nur sultan","akmola"], "Nairobi",
      ["Tarawa","tarawa","south tarawa"], "Pyongyang", "Seoul", "Pristina", "Kuwait City", ["Bishkek","bishkek","frunze"],
      "Vientiane", "Riga", "Beirut", "Maseru", "Monrovia", "Tripoli", "Vaduz", "Vilnius",
      ["Luxembourg","luxembourg","luxembourg city"], "Antananarivo", "Lilongwe", ["Kuala Lumpur","kuala lumpur","putrajaya"],
      "Malé", "Bamako", "Valletta", "Majuro", "Nouakchott", "Port Louis", "Mexico City", "Palikir",
      ["Chișinău","chisinau","kishinev"], "Monaco", ["Ulaanbaatar","ulaanbaatar","ulan bator"], "Podgorica", "Rabat",
      "Maputo", ["Naypyidaw","naypyidaw","nay pyi taw","naypyitaw"], "Windhoek", "Yaren", "Kathmandu", "Amsterdam",
      "Wellington", "Managua", "Niamey", "Abuja", "Skopje", "Oslo", "Muscat", "Islamabad", "Ngerulmud", "Panama City",
      "Port Moresby", "Asunción", "Lima", "Manila", "Warsaw", "Lisbon", "Doha", "Bucharest", "Moscow", "Kigali",
      "Basseterre", "Castries", "Kingstown", "Apia", ["San Marino","san marino","city of san marino"], "São Tomé",
      "Riyadh", "Dakar", "Belgrade", "Victoria", "Freetown", "Singapore", "Bratislava", "Ljubljana", "Honiara", "Mogadishu",
      ["Pretoria","pretoria","cape town","bloemfontein"], "Juba", "Madrid",
      ["Sri Jayawardenepura Kotte","sri jayawardenepura kotte","colombo","kotte"], "Khartoum", "Paramaribo", "Stockholm",
      ["Bern","bern","berne"], "Damascus", "Dushanbe", ["Dodoma","dodoma","dar es salaam"], "Bangkok", "Dili", "Lomé",
      ["Nuku'alofa","nuku'alofa","nukualofa"], ["Port of Spain","port of spain","port-of-spain"], "Tunis", "Ankara",
      "Ashgabat", "Funafuti", "Kampala", ["Kyiv","kyiv","kiev"], "Abu Dhabi", "London",
      ["Washington, D.C.","washington","washington dc","washington d.c."], "Montevideo", "Tashkent", "Port Vila",
      ["Vatican City","vatican city","vatican"], "Caracas", "Hanoi", ["Sanaa","sanaa","sana'a"], "Lusaka", "Harare",
    ]},
    { name: "Countries in Asia", items: [
      "China","India","Japan","South Korea","North Korea","Vietnam","Thailand","Cambodia","Laos","Myanmar","Malaysia",
      "Singapore","Indonesia","Philippines","Mongolia","Kazakhstan","Uzbekistan","Turkmenistan","Kyrgyzstan","Tajikistan",
      "Afghanistan","Pakistan","Bangladesh","Sri Lanka","Nepal","Bhutan","Iran","Iraq","Saudi Arabia","Yemen","Oman",
      ["United Arab Emirates","uae","united arab emirates"], "Qatar","Bahrain","Kuwait","Jordan","Israel","Lebanon",
      "Syria","Turkey","Georgia","Armenia","Azerbaijan","Brunei","Taiwan","Maldives",
    ]},
    { name: "Countries in Africa", exact: true, items: [
      "Algeria","Angola","Benin","Botswana","Burkina Faso","Burundi", ["Cabo Verde","cabo verde","cape verde"],
      "Cameroon", ["Central African Republic","central african republic","car"], "Chad","Comoros",
      ["Republic of the Congo","republic of the congo","congo-brazzaville","congo brazzaville"],
      ["DR Congo","dr congo","democratic republic of the congo","drc","congo-kinshasa","congo kinshasa"],
      ["Côte d'Ivoire","cote d'ivoire","cote divoire","ivory coast"], "Djibouti","Egypt","Equatorial Guinea","Eritrea",
      ["Eswatini","eswatini","swaziland"], "Ethiopia","Gabon", ["The Gambia","the gambia","gambia"], "Ghana","Guinea",
      ["Guinea-Bissau","guinea-bissau","guinea bissau"], "Kenya","Lesotho","Liberia","Libya","Madagascar","Malawi","Mali",
      "Mauritania","Mauritius","Morocco","Mozambique","Namibia","Niger","Nigeria","Rwanda",
      ["São Tomé and Príncipe","sao tome and principe","sao tome"], "Senegal","Seychelles","Sierra Leone","Somalia",
      "South Africa","South Sudan","Sudan","Tanzania","Togo","Tunisia","Uganda","Zambia","Zimbabwe",
    ]},
    { name: "Countries in South America", exact: true, items: [
      "Brazil","Argentina","Chile","Peru","Colombia","Venezuela","Ecuador","Bolivia","Paraguay","Uruguay","Guyana","Suriname",
    ]},
    { name: "Natural Disasters", items: [
      "Earthquake","Tsunami","Hurricane","Tornado","Flood", ["Wildfire","wildfire","forest fire"],
      ["Volcanic Eruption","volcanic eruption","volcano","eruption"], "Drought","Blizzard","Landslide","Avalanche",
      "Mudslide","Cyclone","Typhoon","Hailstorm","Sinkhole","Heatwave","Thunderstorm", ["Tropical Storm","tropical storm"],
      "Famine", ["Sandstorm","sandstorm","dust storm"], "Ice Storm","Storm Surge","Lightning Strike",
    ]},
    { name: "Major Rivers", items: [
      "Nile", ["Amazon","amazon","amazon river"], ["Yangtze","yangtze","yangtze river"],
      ["Mississippi","mississippi","mississippi river"], "Danube","Volga","Ganges","Mekong","Congo","Rhine","Niger",
      "Yellow River", ["Yenisei","yenisei","yenisey"], "Ob", ["Paraná","parana"], "Amur","Lena","Murray","Indus",
      "Brahmaputra","Euphrates","Tigris","Zambezi","Colorado","Rio Grande","Seine","Thames","Tiber","Po","Yukon",
    ]},
    { name: "Famous Mountains", items: [
      ["Mount Everest","everest","mount everest"], "K2","Kangchenjunga", ["Kilimanjaro","kilimanjaro","mount kilimanjaro"],
      "Mont Blanc","Matterhorn", ["Denali","denali","mount mckinley"], ["Fuji","fuji","mount fuji","mt fuji"],
      "Aconcagua","Annapurna","Nanga Parbat","Eiger","Mount Rainier","Mount Etna","Mount Vesuvius","Mount Olympus",
      "Mount Elbrus","Mount Kosciuszko","Pikes Peak","Mount Whitney","Table Mountain","Half Dome","Ben Nevis","Mount Cook",
      "Mount Logan",
    ]},
    { name: "Deserts", items: [
      "Sahara","Gobi","Kalahari","Mojave","Atacama", ["Arabian Desert","arabian desert","arabian"], "Sonoran","Namib",
      "Thar","Patagonian Desert", ["Great Victoria Desert","great victoria desert","great victoria"],
      "Great Sandy Desert","Karakum","Kyzylkum","Taklamakan","Chihuahuan","Syrian Desert","Death Valley",
      "Antarctic Desert","Arctic Desert",
    ]},
    { name: "Seas and Oceans", items: [
      ["Pacific Ocean","pacific ocean","pacific"], ["Atlantic Ocean","atlantic ocean","atlantic"],
      ["Indian Ocean","indian ocean","indian"], ["Arctic Ocean","arctic ocean","arctic"],
      ["Southern Ocean","southern ocean","antarctic ocean"], ["Mediterranean Sea","mediterranean sea","mediterranean"],
      ["Caribbean Sea","caribbean sea","caribbean"], ["Red Sea","red sea"], ["Black Sea","black sea"],
      ["Baltic Sea","baltic sea","baltic"], ["Caspian Sea","caspian sea","caspian"], ["North Sea","north sea"],
      ["Arabian Sea","arabian sea"], ["South China Sea","south china sea"], ["East China Sea","east china sea"],
      ["Yellow Sea","yellow sea"], ["Sea of Japan","sea of japan"], ["Bering Sea","bering sea"], ["Coral Sea","coral sea"],
      ["Tasman Sea","tasman sea"], ["Sea of Okhotsk","sea of okhotsk"], ["Andaman Sea","andaman sea"],
      ["Adriatic Sea","adriatic sea","adriatic"], ["Aegean Sea","aegean sea","aegean"], ["Sargasso Sea","sargasso sea"],
    ]},
    { name: "Countries in Oceania", exact: true, items: [
      "Australia","New Zealand","Papua New Guinea","Fiji","Solomon Islands","Vanuatu","Samoa","Tonga","Kiribati",
      ["Micronesia","micronesia","federated states of micronesia","fsm"], ["Marshall Islands","marshall islands","marshalls"],
      "Palau","Nauru","Tuvalu",
    ]},
  ]},
  History: { emoji: "🏛️", cats: [
    { name: "US Presidents", items: [
      ["George Washington","george washington","washington"], ["John Adams","john adams","adams"],
      ["Thomas Jefferson","thomas jefferson","jefferson"], ["James Madison","james madison","madison"],
      ["James Monroe","james monroe","monroe"], ["Andrew Jackson","andrew jackson","jackson"],
      ["Abraham Lincoln","abraham lincoln","lincoln"], ["Ulysses S. Grant","ulysses s grant","ulysses grant","grant"],
      ["Theodore Roosevelt","theodore roosevelt","teddy roosevelt"],
      ["Franklin D. Roosevelt","franklin d roosevelt","franklin roosevelt","fdr"], ["Harry Truman","harry truman","truman"],
      ["Dwight Eisenhower","dwight eisenhower","eisenhower"], ["John F. Kennedy","john f kennedy","jfk","kennedy"],
      ["Lyndon B. Johnson","lyndon johnson","lbj"], ["Richard Nixon","richard nixon","nixon"],
      ["Gerald Ford","gerald ford","ford"], ["Jimmy Carter","jimmy carter","carter"],
      ["Ronald Reagan","ronald reagan","reagan"], ["George H. W. Bush","george h w bush","george bush sr"],
      ["Bill Clinton","bill clinton","clinton"], ["George W. Bush","george w bush","dubya"],
      ["Barack Obama","barack obama","obama"], ["Donald Trump","donald trump","trump"], ["Joe Biden","joe biden","biden"],
      ["Woodrow Wilson","woodrow wilson","wilson"], ["William Taft","william taft","taft"],
      ["Herbert Hoover","herbert hoover","hoover"], ["Calvin Coolidge","calvin coolidge","coolidge"],
      ["James Polk","james polk","polk"], ["William McKinley","william mckinley","mckinley"],
    ]},
    { name: "Wars in History", items: [
      ["World War I","world war i","world war 1","wwi","ww1","first world war"],
      ["World War II","world war ii","world war 2","wwii","ww2","second world war"],
      ["American Civil War","american civil war","civil war"],
      ["American Revolution","american revolution","revolutionary war"], "Cold War",
      ["Vietnam War","vietnam war","vietnam"], ["Korean War","korean war","korea"], "Gulf War", "War of 1812",
      "Napoleonic Wars", "Crimean War", ["Hundred Years' War","hundred years war","hundred years' war"],
      ["Thirty Years' War","thirty years war","thirty years' war"], ["Seven Years' War","seven years war"],
      "Spanish Civil War", "Boer War", "Iraq War", "Falklands War",
      ["Russo-Japanese War","russo-japanese war"], "Peloponnesian War",
    ]},
    { name: "Ancient Civilizations", items: [
      ["Roman Empire","roman empire","rome","romans","roman"], ["Ancient Greece","ancient greece","greece","greek","greeks"],
      ["Ancient Egypt","ancient egypt","egypt","egyptian","egyptians"], ["Mesopotamia","mesopotamia","mesopotamian"],
      ["Persian Empire","persian empire","persia","persian"], ["Maya","maya","mayan","mayans"], ["Aztec","aztec","aztecs"],
      ["Inca","inca","incan","incas"], ["Babylon","babylon","babylonian"], ["Sumer","sumer","sumerian","sumerians"],
      ["Assyria","assyria","assyrian"], ["Phoenicia","phoenicia","phoenician"],
      ["Byzantine Empire","byzantine empire","byzantine","byzantium"],
      ["Ottoman Empire","ottoman empire","ottoman","ottomans"], ["Mongol Empire","mongol empire","mongol","mongols"],
      ["Vikings","vikings","viking","norse"], ["Celts","celts","celtic"], ["Carthage","carthage","carthaginian"],
      ["Minoans","minoans","minoan"], ["Olmec","olmec","olmecs"], ["Hittites","hittites","hittite"],
    ]},
    { name: "Historical Figures", items: [
      ["Napoleon","napoleon","napoleon bonaparte"], ["Julius Caesar","julius caesar","caesar"], "Cleopatra",
      ["Alexander the Great","alexander the great"], ["Genghis Khan","genghis khan"],
      ["Abraham Lincoln","abraham lincoln","lincoln"], "George Washington", ["Winston Churchill","winston churchill","churchill"],
      ["Gandhi","gandhi","mahatma gandhi"], ["Martin Luther King Jr.","martin luther king","mlk"],
      ["Albert Einstein","albert einstein","einstein"], ["Isaac Newton","isaac newton","newton"], "Galileo",
      ["Leonardo da Vinci","leonardo da vinci","da vinci"], "Michelangelo",
      ["Christopher Columbus","christopher columbus","columbus"], ["Joan of Arc","joan of arc"], "Queen Victoria",
      ["Henry VIII","henry viii","henry the 8th"], "Marco Polo", "Confucius", "Aristotle", "Plato", "Socrates",
      ["William Shakespeare","william shakespeare","shakespeare"], ["Nelson Mandela","nelson mandela","mandela"],
      ["Benjamin Franklin","benjamin franklin","ben franklin"], ["Thomas Edison","thomas edison","edison"],
      ["Nikola Tesla","nikola tesla","tesla"], ["Charles Darwin","charles darwin","darwin"], "Marie Curie",
      ["Adolf Hitler","adolf hitler","hitler"], ["Joseph Stalin","joseph stalin","stalin"], ["Mao Zedong","mao zedong","mao"],
      ["Karl Marx","karl marx","marx"],
    ]},
    { name: "Famous Explorers", items: [
      ["Christopher Columbus","christopher columbus","columbus"], ["Ferdinand Magellan","ferdinand magellan","magellan"],
      ["Marco Polo","marco polo"], ["Vasco da Gama","vasco da gama","da gama"],
      ["James Cook","james cook","captain cook","cook"], ["Amerigo Vespucci","amerigo vespucci","vespucci"],
      ["Hernán Cortés","hernan cortes","cortes"], ["Francisco Pizarro","francisco pizarro","pizarro"],
      ["Leif Erikson","leif erikson","leif ericson"], ["Zheng He","zheng he"],
      ["Roald Amundsen","roald amundsen","amundsen"], ["Ernest Shackleton","ernest shackleton","shackleton"],
      ["Henry Hudson","henry hudson","hudson"], ["John Cabot","john cabot","cabot"],
      ["Bartolomeu Dias","bartolomeu dias","dias"], ["Francis Drake","francis drake","sir francis drake","drake"],
      ["Juan Ponce de León","ponce de leon"], ["Hernando de Soto","hernando de soto","de soto"],
      ["Jacques Cartier","jacques cartier","cartier"], ["David Livingstone","david livingstone","livingstone"],
      ["Ibn Battuta","ibn battuta"], ["Edmund Hillary","edmund hillary","hillary"],
      ["Tenzing Norgay","tenzing norgay","tenzing"], ["Lewis and Clark","lewis and clark"], ["Robert Peary","robert peary","peary"],
    ]},
    { name: "Famous Battles", items: [
      ["Hastings","hastings","battle of hastings"], ["Waterloo","waterloo","battle of waterloo"],
      ["Gettysburg","gettysburg","battle of gettysburg"], ["Stalingrad","stalingrad","battle of stalingrad"],
      ["D-Day","d-day","dday","normandy","battle of normandy"], ["Thermopylae","thermopylae","battle of thermopylae"],
      ["Agincourt","agincourt","battle of agincourt"], ["Battle of the Bulge","battle of the bulge","the bulge"],
      ["Midway","midway","battle of midway"], ["Trafalgar","trafalgar","battle of trafalgar"],
      ["Bunker Hill","bunker hill","battle of bunker hill"], ["Marathon","marathon","battle of marathon"],
      ["Battle of Britain","battle of britain"], ["Pearl Harbor","pearl harbor","pearl harbour"],
      ["The Somme","somme","battle of the somme"], ["Verdun","verdun","battle of verdun"],
      ["Antietam","antietam","battle of antietam"], ["Saratoga","saratoga","battle of saratoga"],
      ["Little Bighorn","little bighorn","battle of little bighorn","little big horn"],
      ["Yorktown","yorktown","battle of yorktown"], ["Cannae","cannae","battle of cannae"],
      ["Bannockburn","bannockburn","battle of bannockburn"],
    ]},
  ]},
  Entertainment: { emoji: "🎬", cats: [
    { name: "Disney / Pixar Movies", items: [
      ["Snow White and the Seven Dwarfs","snow white"], "Pinocchio", "Fantasia", "Dumbo", "Bambi", "Cinderella",
      ["Alice in Wonderland","alice"], "Peter Pan", "Lady and the Tramp", ["Sleeping Beauty","aurora"],
      ["One Hundred and One Dalmatians","101 dalmatians","one hundred and one dalmatians"],
      ["The Sword in the Stone","sword in the stone"], ["The Jungle Book","jungle book"], ["The Aristocats","aristocats"],
      ["Robin Hood","disney robin hood"], ["The Many Adventures of Winnie the Pooh","winnie the pooh"],
      ["The Rescuers","rescuers"], ["The Fox and the Hound","fox and the hound"], ["The Black Cauldron","black cauldron"],
      ["The Great Mouse Detective","great mouse detective"], "Oliver and Company", ["The Little Mermaid","little mermaid"],
      ["The Rescuers Down Under","rescuers down under"], "Beauty and the Beast", "Aladdin", ["The Lion King","lion king"],
      "Pocahontas", ["The Hunchback of Notre Dame","hunchback of notre dame","hunchback"], "Hercules", "Mulan", "Tarzan",
      "Fantasia 2000", "Dinosaur", ["The Emperor's New Groove","emperors new groove"], "Atlantis: The Lost Empire",
      "Lilo and Stitch", ["Treasure Planet","treasure planet"], ["Brother Bear","brother bear"], "Home on the Range",
      ["Chicken Little","chicken little"], "Meet the Robinsons", "Bolt", ["The Princess and the Frog","princess and the frog"],
      "Tangled", ["Wreck-It Ralph","wreck it ralph"], "Frozen", ["Big Hero 6","big hero six"], "Zootopia", "Moana",
      ["Ralph Breaks the Internet","ralph breaks the internet","wreck it ralph 2"], ["Frozen II","frozen 2"],
      "Raya and the Last Dragon", "Encanto", "Strange World", "Wish", "Toy Story", "A Bug's Life",
      ["Toy Story 2","toy story two"], ["Monsters, Inc.","monsters inc"], ["Finding Nemo","nemo"],
      ["The Incredibles","incredibles"], "Cars", "Ratatouille", ["WALL-E","wall e","walle"], "Up",
      ["Toy Story 3","toy story three"], "Cars 2", "Brave", "Monsters University", "Inside Out",
      ["The Good Dinosaur","good dinosaur"], "Finding Dory", "Cars 3", "Coco", "Incredibles 2",
      ["Toy Story 4","toy story four"], "Onward", "Soul", "Luca", "Turning Red", "Lightyear", "Elemental", "Inside Out 2",
    ]},
    { name: "Marvel Superheroes", items: [
      ["Iron Man","iron man","tony stark"], ["Captain America","captain america","steve rogers"],
      ["Thor","thor","god of thunder"], ["Hulk","hulk","bruce banner","incredible hulk"],
      ["Black Widow","black widow","natasha romanoff"], ["Hawkeye","hawkeye","clint barton"],
      ["Spider-Man","spider man","spiderman","peter parker"], ["Doctor Strange","doctor strange","dr strange","stephen strange"],
      ["Black Panther","black panther","tchalla"], ["Scarlet Witch","scarlet witch","wanda maximoff","wanda"], "Vision",
      ["Ant-Man","ant man","scott lang"], ["Wasp","the wasp","hope van dyne"], ["Star-Lord","star lord","peter quill"],
      "Gamora", ["Groot","groot","i am groot"], ["Rocket Raccoon","rocket","rocket raccoon"],
      ["Drax","drax","drax the destroyer"], "Mantis", "Nebula", ["Falcon","falcon","sam wilson"],
      ["Winter Soldier","winter soldier","bucky","bucky barnes"], ["Captain Marvel","captain marvel","carol danvers"],
      ["Wolverine","wolverine","logan"], ["Deadpool","deadpool","wade wilson"], ["Storm","storm","ororo munroe"],
      ["Cyclops","cyclops","scott summers"], ["Jean Grey","jean grey","phoenix","dark phoenix"], ["Beast","beast","hank mccoy"],
      "Rogue", "Gambit", "Nightcrawler", ["Professor X","professor x","charles xavier","professor xavier"],
      ["Magneto","magneto","erik lehnsherr"], ["Daredevil","daredevil","matt murdock"],
      ["Punisher","punisher","the punisher","frank castle"], ["Loki","loki","god of mischief"], ["Nick Fury","nick fury","fury"],
      ["War Machine","war machine","james rhodes","rhodey"], ["Quicksilver","quicksilver","pietro maximoff"],
      ["Shang-Chi","shang chi"], ["Moon Knight","moon knight","marc spector"], ["Thanos","thanos","mad titan"],
      ["Venom","venom","eddie brock"], ["Green Goblin","green goblin","norman osborn"],
      ["Doctor Octopus","doctor octopus","doc ock","otto octavius"], ["Magik","magik","illyana"],
      ["Iceman","iceman","bobby drake"], "Jubilee", "Colossus", "Psylocke", "Mystique", "Sabretooth", "Juggernaut",
      "Ultron", "Red Skull", ["Ghost Rider","ghost rider","johnny blaze"], "Blade", ["The Thing","the thing","ben grimm"],
      ["Mr. Fantastic","mr fantastic","reed richards"], ["Invisible Woman","invisible woman","sue storm"],
      ["Human Torch","human torch","johnny storm"], "Silver Surfer",
      ["Doctor Doom","doctor doom","victor von doom","dr doom"], ["Kang","kang","kang the conqueror"],
      ["Carnage","carnage","cletus kasady"], ["Gwen Stacy","gwen stacy","spider gwen","ghost spider"],
      "Miles Morales", ["Iron Fist","iron fist","danny rand"], "Luke Cage", "Jessica Jones",
      ["Kingpin","kingpin","wilson fisk"], "Wong", ["Yelena Belova","yelena","yelena belova"],
      ["Kraven","kraven","kraven the hunter"], "Sandman", ["Mister Sinister","mister sinister","mr sinister"], "Bishop",
    ]},
    { name: "Popular Movies", items: [
      "Titanic", "Avatar", ["The Godfather","godfather"], "Jaws", ["Star Wars","a new hope","star wars episode iv"],
      "Jurassic Park", "Forrest Gump", ["The Matrix","matrix"], "Inception", "Interstellar", "Gladiator", "Pulp Fiction",
      "Goodfellas", "Fight Club", ["The Dark Knight","dark knight"], "Joker", ["The Avengers","avengers"],
      ["Avengers: Endgame","endgame","avengers endgame"], ["Avengers: Infinity War","infinity war","avengers infinity war"],
      "Top Gun", ["Top Gun: Maverick","top gun maverick","maverick"], "Jurassic World",
      ["Harry Potter and the Sorcerer's Stone","harry potter","sorcerers stone","philosophers stone"],
      ["The Lord of the Rings: The Fellowship of the Ring","lord of the rings","lotr","fellowship of the ring"],
      ["The Lord of the Rings: The Two Towers","two towers"], ["The Lord of the Rings: The Return of the King","return of the king"],
      ["The Hobbit","hobbit"], "Frozen", "Shrek", "Toy Story", "Home Alone", "Die Hard", ["The Terminator","terminator"],
      ["Terminator 2: Judgment Day","terminator 2","t2"], "Alien", "Aliens", "Rocky", ["Back to the Future","bttf"],
      ["Raiders of the Lost Ark","indiana jones","raiders of the lost ark"],
      ["E.T. the Extra-Terrestrial","et","e t","et the extra terrestrial"], "Ghostbusters", "Parasite", "Get Out",
      "La La Land", "Whiplash", "Oppenheimer", "Barbie", "Dune", ["Dune: Part Two","dune 2","dune part two"],
      ["The Shawshank Redemption","shawshank redemption","shawshank"], ["The Silence of the Lambs","silence of the lambs"],
      ["Schindler's List","schindlers list"], "Saving Private Ryan", ["The Lion King","lion king"],
      ["The Wizard of Oz","wizard of oz"], "Casablanca", "Gone with the Wind", "Psycho", ["The Departed","departed"],
      ["Django Unchained","django"], "Inglourious Basterds", "No Country for Old Men", "Braveheart",
      ["Mad Max: Fury Road","mad max fury road","fury road","mad max"], ["The Wolf of Wall Street","wolf of wall street"],
      ["Black Panther","black panther movie"], ["Spider-Man: No Way Home","no way home","spiderman no way home"],
      "Guardians of the Galaxy", "Deadpool", ["The Lego Movie","lego movie"], "Frozen II", "Moana", "Encanto",
      ["Finding Nemo","nemo"], "Despicable Me", "Minions", "Coco", "Up", ["WALL-E","wall e"], ["The Incredibles","incredibles"],
      ["Pirates of the Caribbean","pirates of the caribbean","potc"], ["The Hunger Games","hunger games"], "Twilight",
      ["The Conjuring","conjuring"], "It", ["A Quiet Place","quiet place"], ["John Wick","john wick 1"],
      ["Mission: Impossible","mission impossible","mi"], ["The Bourne Identity","bourne identity","bourne"], "Casino Royale",
      ["Skyfall","skyfall","james bond"], ["The Notebook","notebook"], "Grease", "Dirty Dancing",
      ["The Sixth Sense","sixth sense"], "Gravity", "The Revenant", "1917", "Everything Everywhere All at Once",
    ]},
    { name: "Star Wars Characters", items: [
      ["Luke Skywalker","luke","luke skywalker"], ["Darth Vader","vader","darth vader"],
      ["Princess Leia","leia","princess leia"], ["Han Solo","han","han solo"], ["Chewbacca","chewie","chewbacca"],
      "Yoda", ["Obi-Wan Kenobi","obi-wan","obi wan","obi-wan kenobi","kenobi"], ["R2-D2","r2-d2","r2d2"],
      ["C-3PO","c-3po","c3po"], ["Emperor Palpatine","palpatine","emperor palpatine"],
      ["Anakin Skywalker","anakin","anakin skywalker"], "Padmé", ["Qui-Gon Jinn","qui-gon","qui gon","qui-gon jinn"],
      "Mace Windu","Jar Jar Binks","Boba Fett","Jango Fett", ["Lando Calrissian","lando","lando calrissian"],
      "Rey","Finn", ["Poe Dameron","poe","poe dameron"], ["Kylo Ren","kylo","kylo ren"], ["BB-8","bb-8","bb8"],
      ["The Mandalorian","mando","the mandalorian","din djarin"], ["Grogu","grogu","baby yoda"],
      ["Ahsoka Tano","ahsoka","ahsoka tano"], "Count Dooku","General Grievous", ["Darth Maul","maul","darth maul"],
      ["Jabba the Hutt","jabba","jabba the hutt"],
    ]},
    { name: "Video Games", items: [
      ["Super Mario Bros.","mario","super mario","super mario bros"], ["The Legend of Zelda","zelda","legend of zelda"],
      "Minecraft", "Fortnite", ["Grand Theft Auto","gta","grand theft auto"], ["Grand Theft Auto V","gta v","gta 5"],
      ["Call of Duty","cod","call of duty"], "Halo", ["Pokémon","pokemon"], "Tetris", ["Pac-Man","pac man","pacman"],
      ["Sonic the Hedgehog","sonic","sonic the hedgehog"], ["Donkey Kong","donkey kong","dk"], "Metroid",
      ["Final Fantasy","final fantasy","ff"], ["The Last of Us","last of us","tlou"], ["God of War","god of war","gow"],
      "Elden Ring", "Dark Souls", ["The Elder Scrolls V: Skyrim","skyrim"], "Fallout", ["The Witcher","witcher","the witcher 3"],
      ["Red Dead Redemption","red dead","rdr","red dead redemption 2","rdr2"], ["Cyberpunk 2077","cyberpunk","cyberpunk 2077"],
      "Overwatch", "Valorant", ["League of Legends","lol","league of legends","league"],
      ["Counter-Strike","cs","counter strike","csgo","cs2"], ["Apex Legends","apex","apex legends"],
      ["EA Sports FC","fifa","ea fc","ea sports fc"], ["Madden NFL","madden","madden nfl"], ["NBA 2K","nba 2k","2k"],
      "Roblox", "Among Us", "Animal Crossing", ["Stardew Valley","stardew valley","stardew"], "Terraria",
      ["Mortal Kombat","mortal kombat","mk"], ["Street Fighter","street fighter","sf"], "Tekken",
      ["Assassin's Creed","assassins creed","ac"], "Far Cry", ["Resident Evil","resident evil","re"], "BioShock", "Portal",
      ["Half-Life","half life"], "Hollow Knight", "Celeste", "Doom", "Diablo", ["World of Warcraft","wow","world of warcraft"],
      ["Candy Crush Saga","candy crush"], "Angry Birds", "Cuphead",
      ["Super Smash Bros.","smash bros","super smash bros","smash"], "Mario Kart", "Splatoon", "Kirby",
      ["Metal Gear Solid","metal gear","mgs","metal gear solid"], "Destiny", "Borderlands", ["Gears of War","gears of war","gears"],
      "Uncharted", "Hades", "Sekiro", "Bloodborne", ["Genshin Impact","genshin","genshin impact"],
      ["Clash of Clans","clash of clans","coc"], "Clash Royale", ["PUBG","pubg","playerunknowns battlegrounds"],
      "Rocket League", "Fall Guys", ["The Sims","the sims","sims"], "Tomb Raider", ["Mega Man","mega man","megaman"],
      "Castlevania", ["Gran Turismo","gran turismo"], ["Need for Speed","need for speed","nfs"], ["Dota 2","dota","dota 2"],
      "Warzone", "Pikmin",
    ]},
    { name: "Video Game Consoles", items: [
      ["PlayStation","playstation","ps1","ps one","psx"], ["PlayStation 2","ps2","playstation 2"],
      ["PlayStation 3","ps3","playstation 3"], ["PlayStation 4","ps4","playstation 4"],
      ["PlayStation 5","ps5","playstation 5"], ["PlayStation Portable","psp"], ["PlayStation Vita","ps vita","vita"],
      ["Xbox","xbox"], ["Xbox 360","xbox 360","360"], ["Xbox One","xbox one"], ["Xbox Series X","series x","xbox series x"],
      ["Xbox Series S","series s","xbox series s"], ["Nintendo Entertainment System","nes","nintendo entertainment system"],
      ["Super Nintendo","snes","super nintendo","super nes"], ["Nintendo 64","n64","nintendo 64"], ["GameCube","gamecube","ngc"],
      ["Nintendo Wii","wii"], ["Wii U","wii u"], ["Nintendo Switch","switch","nintendo switch"], ["Nintendo Switch 2","switch 2"],
      ["Game Boy","game boy","gameboy"], ["Game Boy Color","game boy color","gbc"], ["Game Boy Advance","gba","game boy advance"],
      ["Nintendo DS","ds","nintendo ds"], ["Nintendo 3DS","3ds","nintendo 3ds"], "Virtual Boy",
      ["Sega Genesis","genesis","sega genesis","mega drive","sega mega drive"], ["Sega Saturn","saturn","sega saturn"],
      ["Sega Dreamcast","dreamcast","sega dreamcast"], ["Sega Game Gear","game gear","sega game gear"],
      ["Sega Master System","master system","sega master system"], ["Atari 2600","atari 2600","atari","2600"],
      ["Atari Jaguar","atari jaguar","jaguar"], ["Atari Lynx","atari lynx","lynx"], "Steam Deck",
      ["Nintendo Switch Lite","switch lite"], "Neo Geo", ["TurboGrafx-16","turbografx","turbografx 16"], "3DO",
      "Intellivision", "ColecoVision", ["Magnavox Odyssey","odyssey","magnavox odyssey"],
      ["Commodore 64","commodore 64","c64"], "Ouya", "Sega CD", ["Nintendo New 3DS","new 3ds"],
    ]},
  ]},
  Food: { emoji: "🍕", cats: [
    { name: "Pizza Toppings", items: [
      ["Pepperoni","pepperoni","pepperonis"], "Cheese", ["Mushroom","mushroom","mushrooms"], ["Onion","onion","onions"],
      "Sausage", "Bacon", "Ham", "Pineapple", ["Olives","olives","olive","black olives"],
      ["Peppers","peppers","green peppers","bell peppers","green pepper"], ["Jalapeño","jalapeno","jalapenos"], "Spinach",
      ["Tomato","tomato","tomatoes"], "Basil", ["Anchovies","anchovies","anchovy"], "Chicken", ["Ground Beef","ground beef","beef"],
      "Garlic", "Feta", "Mozzarella", "Prosciutto", "Arugula", "Corn", ["Artichoke","artichoke","artichokes"], "Pesto",
      "Salami", ["Meatball","meatball","meatballs"], ["Banana Pepper","banana pepper","banana peppers"],
      ["Roasted Red Pepper","roasted red pepper","roasted red peppers"], "Ricotta", ["Egg","egg","eggs"],
      ["Pulled Pork","pulled pork"], "Shrimp", "Tuna", ["Capers","capers","caper"],
      ["Sun-dried Tomato","sun dried tomato","sundried tomato","sun-dried tomato","sun dried tomatoes"], "Broccoli",
      ["Eggplant","eggplant","aubergine"], ["Zucchini","zucchini","courgette"], ["Hot Honey","hot honey"],
    ]},
    { name: "Fruits", items: [
      ["Apple","apple","apples"], ["Banana","banana","bananas"], ["Orange","orange","oranges"], ["Grape","grape","grapes"],
      ["Strawberry","strawberry","strawberries"], ["Blueberry","blueberry","blueberries"], ["Raspberry","raspberry","raspberries"],
      ["Blackberry","blackberry","blackberries"], ["Mango","mango","mangoes","mangos"], ["Pineapple","pineapple","pineapples"],
      ["Watermelon","watermelon","watermelons"], ["Melon","melon","melons"], ["Cantaloupe","cantaloupe","cantaloupes"],
      ["Kiwi","kiwi","kiwis","kiwifruit"], ["Peach","peach","peaches"], ["Pear","pear","pears"], ["Plum","plum","plums"],
      ["Cherry","cherry","cherries"], ["Lemon","lemon","lemons"], ["Lime","lime","limes"],
      ["Grapefruit","grapefruit","grapefruits"], ["Pomegranate","pomegranate","pomegranates"], ["Papaya","papaya","papayas"],
      ["Guava","guava","guavas"], ["Apricot","apricot","apricots"], ["Fig","fig","figs"], ["Date","date","dates"],
      ["Coconut","coconut","coconuts"], ["Avocado","avocado","avocados"], ["Passion Fruit","passion fruit","passionfruit"],
      ["Dragon Fruit","dragon fruit","dragonfruit"], ["Lychee","lychee","lychees","litchi"], ["Cranberry","cranberry","cranberries"],
      ["Gooseberry","gooseberry","gooseberries"], ["Nectarine","nectarine","nectarines"], ["Tangerine","tangerine","tangerines"],
      ["Clementine","clementine","clementines"], ["Persimmon","persimmon","persimmons"],
      ["Mandarin","mandarin","mandarins","mandarin orange"], "Honeydew", ["Currant","currant","currants"],
      ["Mulberry","mulberry","mulberries"], ["Elderberry","elderberry","elderberries"], ["Starfruit","starfruit","star fruit"],
      "Jackfruit", ["Plantain","plantain","plantains"], "Quince", ["Boysenberry","boysenberry","boysenberries"], "Tamarind",
      ["Cactus Pear","cactus pear","prickly pear"],
    ]},
    { name: "Vegetables", items: [
      ["Carrot","carrot","carrots"], "Broccoli", "Spinach", "Lettuce", "Kale", "Cabbage", "Cauliflower",
      ["Potato","potato","potatoes"], ["Sweet Potato","sweet potato","sweet potatoes","yam","yams"], ["Tomato","tomato","tomatoes"],
      ["Cucumber","cucumber","cucumbers"], ["Onion","onion","onions"], "Garlic",
      ["Bell Pepper","bell pepper","pepper","peppers","bell peppers"], "Celery", "Asparagus",
      ["Zucchini","zucchini","courgette","zucchinis"], ["Eggplant","eggplant","aubergine"], ["Mushroom","mushroom","mushrooms"],
      ["Corn","corn","maize","sweetcorn"], ["Peas","peas","pea"], ["Green Beans","green beans","green bean","string beans"],
      ["Beet","beet","beets","beetroot"], ["Radish","radish","radishes"], ["Turnip","turnip","turnips"],
      ["Brussels Sprouts","brussels sprouts","brussel sprouts","brussels sprout"], ["Artichoke","artichoke","artichokes"],
      ["Leek","leek","leeks"], "Okra", ["Pumpkin","pumpkin","pumpkins"], ["Squash","squash"], ["Parsnip","parsnip","parsnips"],
      ["Arugula","arugula","rocket"], ["Swiss Chard","swiss chard","chard"], ["Bok Choy","bok choy","pak choi"], "Fennel",
      ["Green Onion","green onion","green onions","scallion","scallions"], ["Shallot","shallot","shallots"],
      ["Cilantro","cilantro","coriander"], ["Collard Greens","collard greens","collards"], "Watercress", "Endive",
      ["Romaine","romaine","romaine lettuce"], ["Iceberg Lettuce","iceberg","iceberg lettuce"],
      ["Butternut Squash","butternut squash"], ["Acorn Squash","acorn squash"], ["Snow Peas","snow peas","snow pea"],
      ["Snap Peas","snap peas","sugar snap peas"], "Ginger", ["Rutabaga","rutabaga","swede"],
      ["Chili Pepper","chili pepper","chilli","chili","chili peppers"],
    ]},
    { name: "Ice Cream Flavors", items: [
      "Vanilla", "Chocolate", "Strawberry",
      ["Mint Chocolate Chip","mint chocolate chip","mint choc chip","mint chip"],
      ["Cookie Dough","cookie dough","cookie dough ice cream"],
      ["Cookies and Cream","cookies and cream","cookies n cream","cookies & cream","oreo"], "Rocky Road", "Butter Pecan",
      "Pistachio", "Neapolitan", "Coffee", "Mango", ["Chocolate Chip","chocolate chip","choc chip"], "Salted Caramel",
      "Caramel", ["Birthday Cake","birthday cake","cake batter"], "Cotton Candy", ["Bubblegum","bubblegum","bubble gum"],
      "Coconut", "Lemon", "Peach", "Banana", ["Cherry","cherry","cherries"], "Black Raspberry", "Moose Tracks", "Superman",
      "Rum Raisin", ["Green Tea","green tea","matcha","matcha green tea"], ["Peanut Butter","peanut butter","pb"], "Fudge",
      ["Brownie","brownie","brownies","brownie batter"], "Cheesecake", "Tiramisu", "Espresso", "Dulce de Leche",
      ["S'mores","smores","s'mores"], ["Pralines and Cream","pralines and cream","praline","pralines n cream"],
      "Chocolate Fudge Brownie", ["Maple","maple","maple walnut"], ["Toffee","toffee","english toffee"],
      ["Raspberry","raspberry","raspberries"], "Almond", "Spumoni", "Butterscotch",
    ]},
    { name: "Desserts", items: [
      ["Cake","cake","cakes"], "Chocolate Cake", "Cheesecake", ["Pie","pie","pies"], "Apple Pie", "Pumpkin Pie",
      ["Brownie","brownie","brownies"], ["Cookie","cookie","cookies"],
      ["Chocolate Chip Cookie","chocolate chip cookie","chocolate chip cookies"], "Ice Cream", ["Cupcake","cupcake","cupcakes"],
      ["Donut","donut","donuts","doughnut","doughnuts"], ["Muffin","muffin","muffins"], "Tiramisu",
      ["Cannoli","cannoli","cannolis"], ["Éclair","eclair","eclairs"], ["Macaron","macaron","macarons"],
      ["Macaroon","macaroon","macaroons"], ["Croissant","croissant","croissants"], ["Pancakes","pancakes","pancake"],
      ["Waffles","waffles","waffle"], ["Crepe","crepe","crepes"], "Pudding", "Custard", "Flan",
      ["Crème Brûlée","creme brulee"], "Mousse", "Chocolate Mousse", "Fudge", ["Truffle","truffle","truffles"], "Gelato",
      ["Sorbet","sorbet","sherbet"], ["Sundae","sundae","sundaes"], ["Milkshake","milkshake","milkshakes","shake"],
      "Banana Split", "Trifle", "Cobbler", "Crumble", ["Tart","tart","tarts"], "Baklava", ["Churros","churros","churro"],
      "Pavlova", "Panna Cotta", ["Strudel","strudel","apple strudel"], "Gingerbread", "Shortcake", "Strawberry Shortcake",
      "Fruitcake", "Banana Bread", ["Scone","scone","scones"], ["Profiterole","profiterole","profiteroles"],
      ["Cinnamon Roll","cinnamon roll","cinnamon rolls","cinnamon bun"], ["Jello","jello","jelly"],
      ["Marshmallow","marshmallow","marshmallows"], "Brioche", ["Lava Cake","lava cake","molten lava cake"],
    ]},
  ]},
  Animals: { emoji: "🐾", cats: [
    { name: "Wild Animals", items: [
      ["Lion","lion","lions"], ["Tiger","tiger","tigers"], ["Elephant","elephant","elephants"], ["Giraffe","giraffe","giraffes"],
      ["Zebra","zebra","zebras"], ["Cheetah","cheetah","cheetahs"], ["Leopard","leopard","leopards"],
      ["Jaguar","jaguar","jaguars"], ["Bear","bear","bears","grizzly","grizzly bear","brown bear"],
      ["Polar Bear","polar bear","polar bears"], ["Panda","panda","pandas","giant panda"],
      ["Wolf","wolf","wolves","gray wolf","grey wolf"], ["Fox","fox","foxes","red fox"], ["Gorilla","gorilla","gorillas"],
      ["Chimpanzee","chimpanzee","chimp","chimps","chimpanzees"], ["Orangutan","orangutan","orangutans","orang utan"],
      ["Kangaroo","kangaroo","kangaroos","roo"], ["Koala","koala","koalas"],
      ["Hippopotamus","hippopotamus","hippo","hippos","hippopotami"], ["Rhinoceros","rhinoceros","rhino","rhinos","rhinoceroses"],
      ["Crocodile","crocodile","crocodiles","croc"], ["Alligator","alligator","alligators","gator"], ["Hyena","hyena","hyenas"],
      ["Wildebeest","wildebeest","wildebeests","gnu"], ["Buffalo","buffalo","buffalos","cape buffalo","water buffalo"],
      ["Bison","bison","bisons"], ["Moose","moose","mooses"], ["Deer","deer","deers"], ["Antelope","antelope","antelopes"],
      ["Gazelle","gazelle","gazelles"], ["Camel","camel","camels"], ["Sloth","sloth","sloths"],
      ["Armadillo","armadillo","armadillos"], ["Anteater","anteater","anteaters"], ["Raccoon","raccoon","raccoons","racoon"],
      ["Otter","otter","otters","sea otter"], ["Beaver","beaver","beavers"], ["Bat","bat","bats"],
      ["Eagle","eagle","eagles","bald eagle"], ["Hawk","hawk","hawks"], ["Owl","owl","owls"],
      ["Falcon","falcon","falcons","peregrine falcon"], ["Penguin","penguin","penguins"], ["Ostrich","ostrich","ostriches"],
      ["Flamingo","flamingo","flamingos","flamingoes"], ["Peacock","peacock","peacocks","peafowl"], ["Toucan","toucan","toucans"],
      ["Parrot","parrot","parrots"], ["Snake","snake","snakes","cobra","python"], ["Lizard","lizard","lizards"],
      ["Komodo Dragon","komodo dragon","komodo dragons","komodo"], ["Iguana","iguana","iguanas"],
      ["Turtle","turtle","turtles","sea turtle"], ["Tortoise","tortoise","tortoises"], ["Frog","frog","frogs"],
      ["Shark","shark","sharks","great white","great white shark"], ["Whale","whale","whales","blue whale","humpback whale"],
      ["Dolphin","dolphin","dolphins"], ["Octopus","octopus","octopuses","octopi"], ["Walrus","walrus","walruses"],
      ["Seal","seal","seals"], ["Meerkat","meerkat","meerkats"], ["Porcupine","porcupine","porcupines"],
    ]},
    { name: "Dog Breeds", items: [
      ["Labrador Retriever","labrador retriever","labrador","lab"], ["Golden Retriever","golden retriever","golden","goldie"],
      ["German Shepherd","german shepherd","gsd","alsatian","german shepard"],
      ["French Bulldog","french bulldog","frenchie","french bull dog"], ["Bulldog","bulldog","english bulldog","british bulldog"],
      ["Poodle","poodle","standard poodle"], "Beagle", ["Rottweiler","rottweiler","rottie","rott"],
      ["Dachshund","dachshund","wiener dog","sausage dog","doxie"], ["Yorkshire Terrier","yorkshire terrier","yorkie"], "Boxer",
      ["Siberian Husky","siberian husky","husky"], ["Great Dane","great dane","dane"],
      ["Doberman Pinscher","doberman pinscher","doberman","dobie"], ["Australian Shepherd","australian shepherd","aussie","aussie shepherd"],
      ["Cavalier King Charles Spaniel","cavalier king charles spaniel","cavalier","king charles spaniel"],
      ["Shih Tzu","shih tzu","shitzu"], ["Pomeranian","pomeranian","pom"], ["Border Collie","border collie","collie"],
      ["Chihuahua","chihuahua","chiwawa"], "Pug", "Boston Terrier",
      ["Pembroke Welsh Corgi","pembroke welsh corgi","corgi","welsh corgi"], ["Bernese Mountain Dog","bernese mountain dog","bernese","berner"],
      ["Cocker Spaniel","cocker spaniel","cocker"], "Maltese", ["Mastiff","mastiff","english mastiff"],
      ["Pit Bull","pit bull","pitbull","pittie","american pit bull terrier"], ["Saint Bernard","saint bernard","st bernard"],
      "Bloodhound", "Weimaraner", "Vizsla", ["Newfoundland","newfoundland","newfie"], "Akita", ["Shiba Inu","shiba inu","shiba"],
      ["Basset Hound","basset hound","basset"], ["Jack Russell Terrier","jack russell terrier","jack russell"],
      ["Australian Cattle Dog","australian cattle dog","blue heeler","heeler","cattle dog"], "Whippet", "Greyhound",
      ["Samoyed","samoyed","sammy"], ["Alaskan Malamute","alaskan malamute","malamute"], ["Chow Chow","chow chow","chow"],
      ["Dalmatian","dalmatian","dalmation"], ["Bichon Frise","bichon frise","bichon"], "Papillon",
      ["Schnauzer","schnauzer","miniature schnauzer"], ["Shar Pei","shar pei","sharpei","chinese shar pei"],
      ["Cane Corso","cane corso","corso"], ["Belgian Malinois","belgian malinois","malinois"], "Irish Setter",
      ["English Springer Spaniel","english springer spaniel","springer spaniel","springer"],
    ]},
  ]},
  Music: { emoji: "🎵", cats: [
    { name: "Rappers", items: [
      "Drake", ["Kendrick Lamar","kendrick","kendrick lamar","k dot","kdot"], ["Kanye West","kanye","ye","kanye west"], "Eminem",
      ["Jay-Z","jay z","jayz","jigga","hova"], ["Lil Wayne","lil wayne","weezy","wayne"], ["Nicki Minaj","nicki minaj","nicki","minaj"],
      ["Travis Scott","travis scott","travis","la flame"], ["J. Cole","j cole","jcole","cole world"],
      ["Post Malone","post malone","posty","post"], ["Cardi B","cardi b","cardi"],
      ["21 Savage","21 savage","21","twenty one savage"], "Future", ["Tyler, the Creator","tyler the creator","tyler creator","tyler"],
      ["Snoop Dogg","snoop dogg","snoop","snoop doggy dogg"], ["Dr. Dre","dr dre","dre","doctor dre"],
      ["50 Cent","50 cent","fifty cent","fitty","curtis jackson"], "Nas",
      ["The Notorious B.I.G.","notorious big","biggie","biggie smalls","notorious b.i.g."],
      ["2Pac","2pac","tupac","tupac shakur","makaveli","pac"], ["Ice Cube","ice cube","cube"],
      ["Megan Thee Stallion","megan thee stallion","megan","meg","thee stallion"], ["Doja Cat","doja cat","doja"],
      ["A$AP Rocky","asap rocky","a$ap rocky","rocky","pretty flacko"], ["Lil Baby","lil baby"], "DaBaby", "Gunna",
      ["Metro Boomin","metro boomin","metro"], ["Childish Gambino","childish gambino","gambino","donald glover"],
      ["Mac Miller","mac miller","mac"], "Logic", ["Big Sean","big sean","sean"], ["Wiz Khalifa","wiz khalifa","wiz"], "Ludacris",
      ["Busta Rhymes","busta rhymes","busta"], ["Rick Ross","rick ross","ross","rozay"],
      ["Juice WRLD","juice wrld","juice world","juice"], ["Lil Uzi Vert","lil uzi vert","lil uzi","uzi"],
      ["Playboi Carti","playboi carti","carti","playboy carti"], ["Lil Durk","lil durk","durk","smurk"], "Pop Smoke",
      ["XXXTentacion","xxxtentacion","xxx"], "Ice Spice", ["Central Cee","central cee","cench","centralcee"],
      ["Method Man","method man","meth","mef"], ["Wu-Tang Clan","wu tang clan","wu tang","wutang","wu"], "Common", "Nelly",
      ["T.I.","ti","t i","tip","clifford harris"], ["Pusha T","pusha t","pusha","king push"],
      ["Kid Cudi","kid cudi","cudi","scott mescudi"], "Tyga", "Offset", "Quavo", "Migos",
      ["Young Thug","young thug","thug","thugger","jeffery"], ["Roddy Ricch","roddy ricch","roddy"],
      ["Jack Harlow","jack harlow","harlow"], "Latto", "GloRilla", "Sexyy Red", ["Lil Nas X","lil nas x","lil nas","nas x"],
      ["Chance the Rapper","chance the rapper","chance","chano"], "Eve", ["Missy Elliott","missy elliott","missy","misdemeanor"],
      ["Lil Kim","lil kim","kim"], ["Run-DMC","run dmc","rundmc"], "Cypress Hill", ["Kodak Black","kodak black","kodak"],
      ["NLE Choppa","nle choppa","nle"], "Polo G", ["Lil Yachty","lil yachty","yachty","lil boat"],
    ]},
    { name: "Pop Stars", items: [
      ["Taylor Swift","taylor swift","taylor","tswift","swift"], ["Beyoncé","beyonce","bey","queen bey"],
      ["Ariana Grande","ariana grande","ariana","ari"], ["Billie Eilish","billie eilish","billie"], ["Dua Lipa","dua lipa","dua"],
      ["Ed Sheeran","ed sheeran","ed"], ["Justin Bieber","justin bieber","bieber","jb","biebs"], ["Bruno Mars","bruno mars","bruno"],
      ["Lady Gaga","lady gaga","gaga"], "Adele", ["Rihanna","rihanna","riri"], ["Katy Perry","katy perry","katy"],
      ["The Weeknd","the weeknd","weeknd","abel"], ["Harry Styles","harry styles","harry"],
      ["Olivia Rodrigo","olivia rodrigo","olivia","livvy"], ["Sabrina Carpenter","sabrina carpenter","sabrina"],
      ["Miley Cyrus","miley cyrus","miley"], ["Selena Gomez","selena gomez","selena","sel"], ["Shawn Mendes","shawn mendes","shawn"],
      ["Sam Smith","sam smith"], "Sia", ["Pink","pink","p!nk"], ["Charlie Puth","charlie puth","charlie"],
      ["Demi Lovato","demi lovato","demi"], "Lizzo", "Halsey", ["Camila Cabello","camila cabello","camila"],
      ["John Legend","john legend","legend"], ["Michael Jackson","michael jackson","mj","king of pop","jacko"], "Madonna",
      ["Whitney Houston","whitney houston","whitney"], ["Mariah Carey","mariah carey","mariah"], ["Elton John","elton john","elton"],
      ["Justin Timberlake","justin timberlake","timberlake","jt"], ["Christina Aguilera","christina aguilera","christina","xtina"],
      ["Britney Spears","britney spears","britney"], ["Lana Del Rey","lana del rey","lana"], "SZA",
      ["Chappell Roan","chappell roan","chappell"], ["Tate McRae","tate mcrae","tate"], "Lorde",
      ["Jonas Brothers","jonas brothers","jonas","nick jonas","jobros"], ["Maroon 5","maroon 5","maroon five","maroon"], "Coldplay",
      ["Stevie Wonder","stevie wonder","stevie"], "Prince", "George Michael", "Cher", ["Celine Dion","celine dion","celine"],
      ["Kelly Clarkson","kelly clarkson","kelly"], ["Gwen Stefani","gwen stefani","gwen"], ["Nicki Minaj","nicki minaj","nicki"],
      ["Doja Cat","doja cat","doja"], ["Janet Jackson","janet jackson","janet"], ["Avril Lavigne","avril lavigne","avril"],
      ["Kesha","kesha","ke$ha"], "Pitbull", "Usher",
    ]},
  ]},
  Brands: { emoji: "🏷️", cats: [
    { name: "Car Brands", items: [
      "Toyota", "Honda", "Ford", ["Chevrolet","chevrolet","chevy"], ["Mercedes-Benz","mercedes-benz","mercedes","benz"],
      ["BMW","bmw","bimmer","beemer"], "Audi", ["Volkswagen","volkswagen","vw"], "Nissan", "Hyundai", "Kia", "Mazda", "Subaru",
      "Lexus", "Porsche", "Ferrari", ["Lamborghini","lamborghini","lambo"], "Tesla", "Jeep", "Dodge", "Ram", "Chrysler", "GMC",
      "Buick", ["Cadillac","cadillac","caddy"], "Lincoln", "Volvo", ["Jaguar","jaguar","jag"],
      ["Land Rover","land rover","landrover","range rover"], "Bentley", ["Rolls-Royce","rolls-royce","rolls royce","rolls"],
      ["Aston Martin","aston martin","aston"], "Maserati", "Bugatti", "McLaren", ["Mini","mini","mini cooper"], "Fiat",
      ["Alfa Romeo","alfa romeo","alfa"], "Peugeot", "Renault", ["Citroën","citroen"], "Acura", "Infiniti", "Genesis",
      ["Mitsubishi","mitsubishi","mitsu"], "Suzuki", ["Corvette","corvette","vette"], "Maybach", "Pagani", "Lotus", "Hummer",
    ]},
    { name: "Tech Companies", items: [
      "Apple", ["Microsoft","microsoft","msft"], ["Alphabet","alphabet","google"], ["Amazon","amazon","aws"],
      ["Meta","meta","facebook","fb"], ["X","x","twitter"], "Nvidia", "Intel", ["AMD","amd","advanced micro devices"], "IBM",
      "Oracle", "Samsung", "Sony", "Netflix", "Adobe", "Salesforce", "Tesla", "Uber", "Lyft", "Airbnb", "Spotify",
      ["Snap","snap","snapchat"], ["TikTok","tiktok","bytedance"], "PayPal", "Cisco", "Qualcomm", "Dell",
      ["HP","hp","hewlett packard","hewlett-packard"], "Lenovo", "Zoom", "Slack", "Dropbox", "Shopify", "Reddit", "Pinterest",
      "LinkedIn", "eBay", "Twitch", "OpenAI", ["Anthropic","anthropic","claude"], "Stripe", ["Square","square","block"],
      "Palantir", "SpaceX", "Broadcom", ["Texas Instruments","texas instruments","ti"], "Micron", "VMware", "ServiceNow",
      "Atlassian", "Huawei",
    ]},
  ]},
};
